In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../dex/clean/final.csv', low_memory=False)
data

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,saldo2,porcent_saldo_venta,porcent_saldo_venta_menor_20,porcent_saldo_venta_20_50,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,825.31,42.124345,0,1,0,6,1,0,0,-0.031054
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,326.92,31.216599,0,1,0,4,0,0,1,-0.193344
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,455.96,15.763327,1,0,0,5,0,0,1,0.135036
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,2078.49,97.688016,0,0,1,7,0,0,1,-0.001076
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,693.30,88.034928,0,0,1,6,0,1,0,-0.239565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0.00,0.000000,1,0,0,1,1,0,0,-0.333046
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,867.09,60.395771,0,0,1,6,1,0,0,-0.124222
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,294.75,100.000000,0,0,1,4,1,0,0,-0.327259
664269,1548603,201901,1,66.050000,1,0.000000,0.00,0.000000,6.683422,0,...,14.24,21.559425,0,1,0,1,0,0,1,-0.367957
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,111.16,100.000000,0,0,1,2,0,0,1,-0.359930

In [3]:
clientes = pd.read_csv('../dex/clientes.csv', delimiter=';', low_memory=False)
clientes

,id,name,type,channel
0,1097501,YURI GOMEZ CADILLO,PANIFICACIÓN,MINORISTAS
1,1156732,ALVARADO BARRERA ROY EDUARDO,MINIMARK./ESTAC.SERV,MINORISTAS
2,583337,ARTICA GARCIA BEATRIZ,BODEGA,MINORISTAS
3,1150752,MENDOZA ANTICONA ENRIQUE,MINIMARK./ESTAC.SERV,MINORISTAS
4,1153420,ARTICA GARCIA BEATRIZ,BODEGAS,MINORISTAS
...,...,...,...,...
799542,512826,CARMEN OTINIANO GUERRERO DE,BODEGA,CADENAS DE FARMACIAS
799543,512849,NUÑEZ CALDERON ROSARIO,BODEGA,CADENAS DE FARMACIAS
799544,512875,ROSABEL CACERES ESPINOZA,BODEGA,CADENAS DE FARMACIAS
799545,1015607,EMP. SERV. MULT. EIRL,BODEGA,MINORISTAS
799546,1051482,GASTON GUZMAN RODRIGUEZ,BODEGA,MINORISTAS

In [4]:
df = data.merge(clientes, left_on=['customer_id'], right_on=['id'], how='left')
df

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,id,name,type,channel
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,0,6,1,0,0,-0.031054,12002.0,MARIA GARCIA SACCACO DE PILLACA,PUESTO DE MERCADO,MINORISTAS
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,0,4,0,0,1,-0.193344,12009.0,GUILLERMINA QUINTANA HUACHACA,BODEGAS,MINORISTAS
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,0,5,0,0,1,0.135036,12045.0,HILDA MORALES ROJAS,PUESTO DE MERCADO,MINORISTAS
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,1,7,0,0,1,-0.001076,12048.0,ISABEL JURO HUAYLLANRE,PUESTO DE MERCADO,MINORISTAS
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,1,6,0,1,0,-0.239565,12050.0,BERTHA BARRIENTOS ROCA,PUESTO DE MERCADO,MINORISTAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0,1,1,0,0,-0.333046,1548555.0,CRISTELL ESTEFANY ZUÑIGA UBILLUS,BODEGAS,MINORISTAS
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,1,6,1,0,0,-0.124222,1548586.0,MIGUEL SALAZAR RUIZ,PUESTO DE MERCADO,MINORISTAS
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,1,4,1,0,0,-0.327259,1548591.0,YENY CANALES PEREZ,BODEGAS,MINORISTAS
664269,1548603,201901,1,66.050000,1,0.000000,0.00,0.000000,6.683422,0,...,0,1,0,0,1,-0.367957,1548603.0,FIDELA DOMINGUEZ ATANACIO DE VASQUEZ,BODEGAS,MINORISTAS
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,1,2,0,0,1,-0.359930,1548619.0,RESGUARDOS J.A.R. S.A.C.,MOSTRADOR,VARIOS

In [5]:
df = df.drop(columns=['id', 'name'])
df

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_menor_20,porcent_saldo_venta_20_50,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,0,1,0,6,1,0,0,-0.031054,PUESTO DE MERCADO,MINORISTAS
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,0,1,0,4,0,0,1,-0.193344,BODEGAS,MINORISTAS
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,1,0,0,5,0,0,1,0.135036,PUESTO DE MERCADO,MINORISTAS
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,0,0,1,7,0,0,1,-0.001076,PUESTO DE MERCADO,MINORISTAS
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,0,0,1,6,0,1,0,-0.239565,PUESTO DE MERCADO,MINORISTAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,1,0,0,1,1,0,0,-0.333046,BODEGAS,MINORISTAS
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,0,0,1,6,1,0,0,-0.124222,PUESTO DE MERCADO,MINORISTAS
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,0,0,1,4,1,0,0,-0.327259,BODEGAS,MINORISTAS
664269,1548603,201901,1,66.050000,1,0.000000,0.00,0.000000,6.683422,0,...,0,1,0,1,0,0,1,-0.367957,BODEGAS,MINORISTAS
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,0,0,1,2,0,0,1,-0.359930,MOSTRADOR,VARIOS

In [6]:
antiguedad = pd.read_csv('../dex/antiguedad.csv', delimiter=';', low_memory=False)
antiguedad

             id creation_date
0         32142    2007-09-03
1         32299    2007-09-03
2         34839    2007-09-03
3         35035    2007-09-03
4        261273    2007-09-03
...         ...           ...
154535  1642852    2021-04-10
154536  1643594    2021-04-16
154537  1643618    2021-04-16
154538  1643619    2021-04-16
154539  1643710    2021-04-17

[154540 rows x 2 columns]

In [7]:
df = df.merge(antiguedad, left_on='customer_id', right_on='id', how='left')
df = df.drop(columns=['id'])

df

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_20_50,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel,creation_date
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,1,0,6,1,0,0,-0.031054,PUESTO DE MERCADO,MINORISTAS,1997-11-06
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,1,0,4,0,0,1,-0.193344,BODEGAS,MINORISTAS,1997-11-06
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,0,0,5,0,0,1,0.135036,PUESTO DE MERCADO,MINORISTAS,1997-11-06
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,0,1,7,0,0,1,-0.001076,PUESTO DE MERCADO,MINORISTAS,1997-11-06
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,0,1,6,0,1,0,-0.239565,PUESTO DE MERCADO,MINORISTAS,1997-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0,0,1,1,0,0,-0.333046,BODEGAS,MINORISTAS,2019-01-28
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,0,1,6,1,0,0,-0.124222,PUESTO DE MERCADO,MINORISTAS,2019-01-28
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,0,1,4,1,0,0,-0.327259,BODEGAS,MINORISTAS,2019-01-28
664269,1548603,201901,1,66.050000,1,0.000000,0.00,0.000000,6.683422,0,...,1,0,1,0,0,1,-0.367957,BODEGAS,MINORISTAS,NaN
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,0,1,2,0,0,1,-0.359930,MOSTRADOR,VARIOS,2019-01-29

In [8]:
df[df['creation_date'].isnull()]

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_20_50,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel,creation_date
17,12467,202003,6,262.960000,4,112.683590,249.78,182.881667,18.605549,4,...,1,0,2,0,0,1,-0.332916,BODEGAS,MINORISTAS,NaN
86,14707,202003,6,998.908333,8,490.039710,1592.84,723.705000,12.390472,5,...,1,0,4,1,0,0,-0.201949,MAYORISTAS,MAYORISTAS,NaN
91,14882,202003,6,692.573333,7,408.276000,1054.30,576.876667,24.383688,0,...,0,1,7,0,1,0,-0.256463,PUESTO DE MERCADO,MINORISTAS,NaN
131,16177,202003,6,1270.945000,8,633.503420,1772.05,1019.858333,26.698177,2,...,0,1,7,0,0,1,-0.153538,PUESTO DE MERCADO,MINORISTAS,NaN
136,16214,202003,5,721.716000,7,105.496511,903.98,721.716000,31.000000,1,...,0,1,6,0,0,1,-0.251277,GASTRONOMÍA,MINORISTAS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664255,1548479,201901,1,421.460000,5,0.000000,421.46,421.460000,31.000000,0,...,0,1,5,1,0,0,-0.304710,GASTRONOMÍA,MINORISTAS,NaN
664257,1548481,201901,1,1098.300000,8,0.000000,1098.30,1098.300000,31.000000,0,...,0,1,7,1,0,0,-0.184261,MAYORISTAS,MAYORISTAS,NaN
664260,1548511,201901,1,3900.180000,10,0.000000,3815.36,3815.360000,15.944869,0,...,0,1,7,1,0,0,0.314353,PUESTO DE MERCADO,MINORISTAS,NaN
664263,1548519,201901,1,119.990000,2,0.000000,119.99,119.990000,31.000000,0,...,0,1,2,1,0,0,-0.358358,GASTRONOMÍA,MINORISTAS,NaN
664269,1548603,201901,1,66.050000,1,0.000000,0.00,0.000000,6.683422,0,...,1,0,1,0,0,1,-0.367957,BODEGAS,MINORISTAS,NaN

In [9]:
df = df[~(df['creation_date'].isnull())]
df

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_20_50,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel,creation_date
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,1,0,6,1,0,0,-0.031054,PUESTO DE MERCADO,MINORISTAS,1997-11-06
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,1,0,4,0,0,1,-0.193344,BODEGAS,MINORISTAS,1997-11-06
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,0,0,5,0,0,1,0.135036,PUESTO DE MERCADO,MINORISTAS,1997-11-06
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,0,1,7,0,0,1,-0.001076,PUESTO DE MERCADO,MINORISTAS,1997-11-06
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,0,1,6,0,1,0,-0.239565,PUESTO DE MERCADO,MINORISTAS,1997-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664265,1548551,201901,1,65.480000,1,0.000000,0.00,0.000000,2.329261,0,...,0,0,1,0,0,1,-0.368059,BODEGAS,MINORISTAS,2019-01-28
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0,0,1,1,0,0,-0.333046,BODEGAS,MINORISTAS,2019-01-28
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,0,1,6,1,0,0,-0.124222,PUESTO DE MERCADO,MINORISTAS,2019-01-28
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,0,1,4,1,0,0,-0.327259,BODEGAS,MINORISTAS,2019-01-28
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,0,1,2,0,0,1,-0.359930,MOSTRADOR,VARIOS,2019-01-29

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 557051 entries, 0 to 664270
Data columns (total 68 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   customer_id                            557051 non-null  int64
 1   var_mes                                557051 non-null  int64
 2   cant_meses_6M                          557051 non-null  int64
 3   venta_tot_mean_6M                      557051 non-null  float64
 4   range_venta                            557051 non-null  int64
 5   venta_tot_std_6M                       557051 non-null  float64
 6   venta_cred_max_6M                      557051 non-null  float64
 7   venta_cred_mean_6M                     557051 non-null  float64
 8   plazo_venta_cred_6M                    557051 non-null  float64
 9   dif_max_venta_cred                     557051 non-null  int64
 10  venta_tot_mean_change                  557051 non-null  float64
 11  venta_tot_mean_change2                 557051 non-null  float64
 12  venta_cred_max_change                  506733 non-null  float64
 13  venta_cred_max_change2                 506733 non-null  float64
 14  flag_venta_tot_mean_change_100         557051 non-null  int64
 15  flag_venta_tot_mean_change_menor_100   557051 non-null  int64
 16  flag_venta_tot_mean_change_mayor_100   557051 non-null  int64
 17  flag_venta_tot_mean_change2_100        557051 non-null  int64
 18  flag_venta_tot_mean_change2_menor_100  557051 non-null  int64
 19  flag_venta_tot_mean_change2_mayor_100  557051 non-null  int64
 20  flag_venta_cred_max_change_0           557051 non-null  int64
 21  flag_venta_cred_max_change_mayor_0     557051 non-null  int64
 22  flag_venta_cred_max_change_null        557051 non-null  int64
 23  flag_venta_cred_max2_change_0          557051 non-null  int64
 24  flag_venta_cred_max2_change_mayor_0    557051 non-null  int64
 25  flag_venta_cred_max2_change_null       557051 non-null  int64
 26  flag_compra_frecuente                  557051 non-null  int64
 27  saldo                                  557051 non-null  float64
 28  tramo                                  557051 non-null  float64
 29  cant_meses_con_deuda_6m                557051 non-null  float64
 30  est_mora_actual                        557051 non-null  int64
 31  est_mora_ant_6m                        557051 non-null  object
 32  segmento                               557051 non-null  object
 33  porcent_deuda_morosa                   557051 non-null  float64
 34  ratio_mora_r3_6m                       557051 non-null  float64
 35  ratio_mora_r5_6m                       557051 non-null  float64
 36  ratio_mora_r7_6m                       557051 non-null  float64
 37  cartera_atrasada                       557051 non-null  float64
 38  tramo_mora_maximo_6m                   557051 non-null  float64
 39  cant_meses_ult_mora                    557051 non-null  float64
 40  porcent_tmp_mas_tot                    557051 non-null  float64
 41  deuda_default                          557051 non-null  float64
 42  flag_default                           557051 non-null  int64
 43  porcentaje_venta_credit_max            557051 non-null  float64
 44  porcentaje_venta_credit_max2           557051 non-null  float64
 45  flag_porcent_venta_cred_max            557051 non-null  int64
 46  flag_porcent_venta_cred_max2           557051 non-null  int64
 47  seg_a                                  557051 non-null  int64
 48  seg_db                                 557051 non-null  int64
 49  seg_c                                  557051 non-null  int64
 50  seg_e                                  557051 non-null  int64
 51  seg_ace                                557051 non-null  int64
 52  seg_b                                  557051 non-null  int64
 53  seg_df                                 557051 non-null  int64
 54  flag_saldo_menor_0                     557051 non-null  int64
 55  saldo2                                 557051 non-null  float64
 56  porcent_saldo_venta                    557051 non-null  float64
 57  porcent_saldo_venta_menor_20           557051 non-null  int64
 58  porcent_saldo_venta_20_50              557051 non-null  int64
 59  porcent_saldo_venta_mayor_50           557051 non-null  int64
 60  range_saldo                            557051 non-null  int64
 61  porcent_deuda_igual_0                  557051 non-null  int64
 62  porcent_deuda_de_0_50                  557051 non-null  int64
 63  porcent_deuda_de_50_100                557051 non-null  int64
 64  venta_mean_6M_scalar                   557051 non-null  float64
 65  type                                   557013 non-null  object
 66  channel                                557013 non-null  object
 67  creation_date                          557051 non-null  object
dtypes: float64(26), int64(37), object(5)
memory usage: 293.2+ MB

In [11]:
df['creation_date'] = df['creation_date'].astype('datetime64')
df['antiguedad'] = ((pd.to_datetime(df['var_mes'], format="%Y%m") + pd.tseries.offsets.MonthEnd(1)) - df['creation_date']).dt.days
df

<ipython-input-11-763e98a6823c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['creation_date'] = df['creation_date'].astype('datetime64')
<ipython-input-11-763e98a6823c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['antiguedad'] = ((pd.to_datetime(df['var_mes'], format="%Y%m") + pd.tseries.offsets.MonthEnd(1)) - df['creation_date']).dt.days

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel,creation_date,antiguedad
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,0,6,1,0,0,-0.031054,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,0,4,0,0,1,-0.193344,BODEGAS,MINORISTAS,1997-11-06,8181
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,0,5,0,0,1,0.135036,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,1,7,0,0,1,-0.001076,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,1,6,0,1,0,-0.239565,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664265,1548551,201901,1,65.480000,1,0.000000,0.00,0.000000,2.329261,0,...,0,1,0,0,1,-0.368059,BODEGAS,MINORISTAS,2019-01-28,3
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0,1,1,0,0,-0.333046,BODEGAS,MINORISTAS,2019-01-28,3
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,1,6,1,0,0,-0.124222,PUESTO DE MERCADO,MINORISTAS,2019-01-28,3
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,1,4,1,0,0,-0.327259,BODEGAS,MINORISTAS,2019-01-28,3
664270,1548619,201901,1,111.160000,2,0.000000,0.00,0.000000,31.000000,0,...,1,2,0,0,1,-0.359930,MOSTRADOR,VARIOS,2019-01-29,2

In [12]:
df['antiguedad'].value_counts()

2498    663
6847    554
1911    544
1973    537
1942    522
       ...
7999      1
8127      1
8176      1
7996      1
8006      1
Name: antiguedad, Length: 8113, dtype: int64

In [13]:
df['type'].value_counts()

BODEGAS                 282308
PUESTO DE MERCADO       128676
GASTRONOMÍA              64480
PANIFICACIÓN             37314
MAYORISTAS               34010
MOSTRADOR                 4152
ALTERN. BODEGAS           4013
MINIMARK./ESTAC.SERV      1920
INSTITUCIONES               92
INDUSTRIAS                  44
SIN ASIGNAR                  3
FARMACIAS                    1
Name: type, dtype: int64

In [14]:
df = df[df['type'].isin(['BODEGAS','PUESTO DE MERCADO','GASTRONOMÍA','PANIFICACIÓN','MAYORISTAS'])]
df

,customer_id,var_mes,cant_meses_6M,venta_tot_mean_6M,range_venta,venta_tot_std_6M,venta_cred_max_6M,venta_cred_mean_6M,plazo_venta_cred_6M,dif_max_venta_cred,...,porcent_saldo_venta_mayor_50,range_saldo,porcent_deuda_igual_0,porcent_deuda_de_0_50,porcent_deuda_de_50_100,venta_mean_6M_scalar,type,channel,creation_date,antiguedad
0,12002,202003,6,1959.223333,9,1591.959310,1442.12,998.520000,20.602923,4,...,0,6,1,0,0,-0.031054,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
1,12009,202003,6,1047.263333,8,263.789981,1144.88,653.860000,15.442213,4,...,0,4,0,0,1,-0.193344,BODEGAS,MINORISTAS,1997-11-06,8181
2,12045,202003,6,2892.536667,10,1371.705600,3933.80,2413.125000,16.784419,4,...,0,5,0,0,1,0.135036,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
3,12048,202003,6,2127.681667,9,990.277619,3515.05,1619.986667,15.885013,0,...,1,7,0,0,1,-0.001076,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
4,12050,202003,6,787.528333,7,152.348331,894.18,701.446667,21.069813,4,...,1,6,0,1,0,-0.239565,PUESTO DE MERCADO,MINORISTAS,1997-11-06,8181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664264,1548542,201901,1,4423.380000,10,0.000000,4423.38,4423.380000,50.272663,0,...,1,8,0,1,0,0.407460,MAYORISTAS,MAYORISTAS,2019-01-28,3
664265,1548551,201901,1,65.480000,1,0.000000,0.00,0.000000,2.329261,0,...,0,1,0,0,1,-0.368059,BODEGAS,MINORISTAS,2019-01-28,3
664266,1548555,201901,1,262.230000,4,0.000000,0.00,0.000000,0.000000,0,...,0,1,1,0,0,-0.333046,BODEGAS,MINORISTAS,2019-01-28,3
664267,1548586,201901,1,1435.680000,9,0.000000,1378.66,1378.660000,18.722689,0,...,1,6,1,0,0,-0.124222,PUESTO DE MERCADO,MINORISTAS,2019-01-28,3
664268,1548591,201901,1,294.750000,4,0.000000,294.75,294.750000,31.000000,0,...,1,4,1,0,0,-0.327259,BODEGAS,MINORISTAS,2019-01-28,3

In [15]:
df_bodegas = df[df['type'] == 'BODEGAS']
df_pdm = df[df['type'] == 'PUESTO DE MERCADO']
df_gastro = df[df['type'] == 'GASTRONOMÍA'] 
df_panif = df[df['type'] == 'PANIFICACIÓN']
df_mayorista = df[df['type'] == 'MAYORISTAS']

In [16]:
df_bodegas.to_csv('../dex/bocas/bodegas.csv', index=False)
df_pdm.to_csv('../dex/bocas/pdm.csv', index=False)
df_gastro.to_csv('../dex/bocas/gastro.csv', index=False)
df_panif.to_csv('../dex/bocas/pani.csv', index=False)
df_mayorista.to_csv('../dex/bocas/mayorista.csv', index=False)